### PR TITLE
Save DifferentiationMethod smoothed values

### PR DESCRIPTION
**Pull request by Jacob-Stevens-Haas**
This change now allows differentiation methods that implicitly smooth x to store that smoothed value in the paramter `smoothed_x_` so that `SINDy` can use it in the feature library.  Currently, this is only `SmoothedFiniteDifference`, but upon acceptance of https://github.com/andgoldschmidt/derivative/pull/15, `SINDyDerivative` where `kind="kalman"` will also implement it.  The hope is that using smoothed coordinate values will help in higher-noise cases.

I've made this a draft PR, however, because the last step is bumping the `derivative` package requirement to whatever is released after that PR is done.  This PR will fail tests until then.  That said, the code itself is ready for review.

# API changes:
* `BaseDifferentiation` and subclasses gain a `smoothed_x_` attribute.
* `SmoothedFiniteDifference` and `SINDyDerivative` gain a kwarg `save_smooth=True`, which can be set to `False` to disable the new behavior (and store the unsmoothed Xs in `smoothed_x_`.
* `BaseFeatureLibrary.calc_trajectory()` (and its subclasses) now return a tuple of `x, x_dot` (the integral for `WeakPDELibrary`) instead of just the second tuple element. ("breaking" change, and the main reason that I tagged the last release of `master` as pre-release)

# Other chages:
* Example 5 (Differentiation Methods) adds Kalman smoothing and shows the effects of using the smoothed x in the feature libraries (it works better, no surprise there)
* Example 5 offloads some plotting code into it's own utils.py module, making the overall notebook easier to read.
* Tests added for API changes.

Sorry for so many PRs :bowtie:... This should be the last major change I submit before my general exam at the end of September.  Only bugfixes and updating notebooks to the new format between now and then.

### CODE REVIEW

**Comment by akaptano** [comment]
@Jacob-Stevens-Haas Is this PR ready for review? Should I merge the most recent main branch into this and give it a look? Sorry this took me a while to get here.

**Comment by akaptano** [comment]
bump!

**Comment by Jacob-Stevens-Haas** [comment]
Oh sorry!  I'm coming back to this research now.  Thanks for keeping me honest :)
I'll review it over the next week to bring it up to speed with the current master branch!

**Comment by znicolaou** [comment]
Good luck @Jacob-Stevens-Haas! Also @akaptano, we may want to prepare a new release soon--some folks have been trying to use the new features from the last couple PRs.  @Jacob-Stevens-Haas, if this PR has a short timeline, we could do them all together. Otherwise, we can do another release in the future.

**Comment by akaptano** [comment]
Yes, I was waiting until the chaotic systems paper finally made it onto arxiv, which it did last night, so I'm happy to do the release this week unless @Jacob-Stevens-Haas thinks this will be a quick turn around.

**Comment by Jacob-Stevens-Haas** [comment]
@znicolaou , looks like you added `plt.ion()` at the beginning of some notebooks, but that causes local tests to pop up dozens of windows.  I can guard it in
```python
if __name__ != "testing":
    ...
else:
    plt.ion()
```
or I can remove it.  Does it help with anything?

**Comment by Jacob-Stevens-Haas** [comment]
This is ready for review @akaptano @znicolaou .  Only thing stopping the CI is the codecov issue

**Comment by znicolaou** [comment]
Nice! I will try to take a look in the next week or so.

**Comment by Jacob-Stevens-Haas** [comment]
@znicolaou @akaptano, now that derivative 0.6.0 has been released, this PR passes tests

**Comment by Jacob-Stevens-Haas** [comment]
Hey @akaptano , @znicolaou , do one of you have time to take a look at this PR?

**Comment by znicolaou** [comment]
Sorry for the delay! Been a couple of busy weeks, but I'm pulling it to check it out now!

**Comment by znicolaou** [comment]
Took an initial look at this tonight. Mostly all good, but we need to merge a couple bug fixes from main in `PDELibrary` and `WeakPDELibrary` from #315 and #321.

**Comment by Jacob-Stevens-Haas** [comment]
Thanks for the look zach!  But WDYM about merging _from main_?  I thought the only conflict is with requirements.txt, since it was removed in #332.  Everything else will be handled when the the PR is merged _into main_.

**Comment by znicolaou** [comment]
Yeah, just giving heads up about changes in master! You can checkout from master before the merge if you want, but just do whatever is easy for you. 

I checked out the examples in notebook 5 too -- looks nice! I think you should probably add a little more description in the markdown cells to describe the new features. Also, the formatting on the first markdown cell got messed up somehow. But anyway, no complaints here, so feel free to merge with master when you're ready.

**Pull request merged**
