### PR TITLE
TST: Add Notebook tests

### PR DESCRIPTION
**Pull request by Jacob-Stevens-Haas**
Tests are skipped by default.  Run `pytest -m "slow"` in order
    to run slow tests.

    Also require upgrading to pytest ~=6.0.0 in order to read
    pyproject.toml configs.

    Change pyproject.toml black table to use extend-exclude, which
    also excludes anything gitignored

To test this change, run
```
pytest --co
```
and
```
pytest --co -m "slow"
```
The first shows that regular testing ignores the notebooks.  The second shows that the tests can be selected.

### CODE REVIEW

**Comment by Jacob-Stevens-Haas** [comment]
Not sure if we want to run notebook tests in CI, but if so, it's as simply as adding `-m "slow and not slow"` to the pytest line in the workflow.  Thoughts?

**Comment by akaptano** [comment]
My only comment is to add some comments to test_notebook since some of the lines are somewhat opaque.

Best,
Alan

**Comment by Jacob-Stevens-Haas** [comment]
Added notebook tests to CI - I'll check the CI report, but if it works, should we remove papermill?

**Comment by akaptano** [comment]
Looks like you need to add sympy as a requirement, fix a timebase issue, etc. to get these tests working.

**Comment by Jacob-Stevens-Haas** [comment]
`sympy` requirement to requirements, or just to GH workflow in order to run this test?

Also, wdym timebase issue?  It looks like the other three failures were 2 dead kernels and 1 ZeroDivisionError (solved in my other PR)

**Comment by akaptano** [comment]
Given what you said about the fix, maybe it is better to merge this in after merging in the other pull request?

**Comment by Jacob-Stevens-Haas** [comment]
Yeah, definitely post #185.  At that point it would be a question of whether we can resolve the DeadKernelError in GH actions, send them to the AMATH server for test, or just skip them.

**Comment by Jacob-Stevens-Haas** [comment]
Added method to refactor and test notebooks _much_ faster by putting data generation in `example_data.py` and putting mock data generation in `mock_data.py`.  See the updated `examples/README.rst`.  Note that these changes require a new development requirement: `jupytext`.  This package allows syncing of .py and .ipynb files.

My thoughts were that we needed:
- debug notebooks in IDE
- Easy diff views of notebooks
- very fast testing of notebooks
- easy for regular users to still use example notebooks out of the box

I think this solution, demonstrated on `examples/2_introduction_to_sindy`, meets all those needs.  A lot of design choices went into this PR that could go various ways, and I'm happy to hear input & change things.

Goal is to get all examples in .py format, then use `examples/publish_notebook.py` to convert the python file to a notebook and run it.  However, for this PR, I would suggest we remove the slow, complete notebook tests from CI, since the current PR is a discrete improvement on previous functionality.  Notebooks can be later converted to the new test-compatible format and will automatically become covered by tests.

@akaptano , @znicolaou , what are your thoughts?

**Comment by Jacob-Stevens-Haas** [comment]
Having trouble with the pre-commit hook for jupytext: https://github.com/mwouts/jupytext/issues/974

**Review by akaptano — APPROVED** [review]

**Comment by akaptano** [comment]
@znicolaou and @Jacob-Stevens-Haas Let's try to get this done this week, and get the release published. I am worried about delaying the release too long, considering the substantial changes that have been made in the past weeks. Thanks for your monumental efforts on the code!

Best,
Alan

**Comment by akaptano** [comment]
Reminder (to myself) that when a new release comes out we need to update all the binder links in the notebooks. Presumably there is some automatic way to do this but it is easy to do, just hard to remember to do!

**Pull request merged**
